#!/bin/bash

set -euo pipefail

[[ "$#" == "0" ]] && echo "You must provide <network> <path>, or just <path>" && exit
[[ "$#" > "2" ]] && echo "You must provide <network> <path>, or just <path>" && exit
network="mainnet"
[[ "$#" == "2" ]] && network=$1 && shift
filePath=$1


stub=$(overflow-generate $1)
if [ $? -ne 0 ]; then
	echo "failed"
	echo $stub
	exit
fi

FILENAME=${1##*/}
interaction="${FILENAME%%.*}"

fileName="cmd_$interaction.go"
echo "$stub" > "$fileName"

${VISUAL:-${EDITOR:-vi}} "${fileName}"

eval "go run $fileName"
#rm $fileName
